# Building a Java project
language: java

# We can specify a list of JDKs to be used for testing
jdk:
 - openjdk11


deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - .travis.yml
  on:
    tags: true
    branch: tag
    repo: <2028942481>/<Travis_CI_Tutorial>


notifications:
 email:
   - 2028942481@qq.com


after_success:
  - bash <(curl -s https://codecov.io/bash)

